name: Deploy to Server

on:
  push:
    branches:
      - stage # Change to your desired branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan 15.206.194.156 >> ~/.ssh/known_hosts
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}

      - name: Install Dependencies and Build
        run: |
          # Install dependencies and build your React app
          export CI=false
          npm install --force
          npm run build
      - name: Deploy Build to Server
        run: |
          # Copy the build artifacts to the server using SCP
          scp -r ./build/* ubuntu@15.206.194.156:/home/ubuntu/web/WebApp_Frontend_User